username = input("Enter your full name:")
# print(username.strip())
# print(username.upper())
# print(username.lower())
# print(username.title())
# print(len(username))
# print(username[:1])
# print(username[4:])
print(username.find("k"))