sentence = input("Enter Your Motto:")
print(len(sentence))
print(len(sentence.split()))
print(sentence[:1])
print(sentence[17:])
print(sentence.upper())
print(sentence.lower())
print(sentence.title())
print(sentence.find("Python"))
print(sentence.count("Once"))