a=True
b=False
#print("True"+"False")
#print("True"-"False")
#print("True"*"False")
#print(True+False)
#print(True-False)
#print(True*False)
#print(True/False)
#print(True//False)
#print(True%False)
print(True**False)